### ISSUE TITLE
support pydantic 2.x conflict with fastapi

### ISSUE THREAD

**Issue by Ben621** [monim67/poetry-bumpversion#10]
hey 
I'm using this library with fastapi that uses pydantic >2 
to update my swagger version

but because you have pinned to a version older than 2 .
I'm unable to use the news feature on fastapi   

Thank you in advance.

**Comment by monim67** [comment]
Thanks for reminding me, I have plans to support pedantic 2 by the end of the week.

**Comment by monim67** [comment]
Published new version 0.3.2 with support for both pydantic 1 & 2.
