### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by ohmycaptainnemo** [monim67/poetry-bumpversion#2]
Hi @monim67 

I was thinking, it would be a good idea to add some unit tests. Similar to this repo:

[https://github.com/tiangolo/poetry-version-plugin](https://github.com/tiangolo/poetry-version-plugin)

**Comment by monim67** [comment]
Good idea, I'll have a go at it when I can. PR's are appreciated too.

**Comment by ohmycaptainnemo** [comment]
> Good idea, I'll have a go at it when I can. PR's are appreciated too.

Thank you. That makes sense.

**Comment by monim67** [comment]
Tests have been added.
