### ISSUE TITLE
How would `self add` support gh actions?

### ISSUE THREAD

**Issue by nrbnlulu** [monim67/poetry-bumpversion#5]
In my understanding it is installed only on poetryies environment.

**Comment by monim67** [comment]
Can you explain the question? What are you trying to accomplish?

**Comment by nrbnlulu** [comment]
>This plugin uses itself in it's "Deploy to PyPI" workflow. When a release tag is created on
GitHub, the workflow updates package version using the release tag name and deploys it to PyPI.
You can copy the `deploy workflow code`_ to your repository to set it up.

How would github actions use this plugin if it is not installed..

**Comment by monim67** [comment]
It's installed by pipx inject, It should also work with poetry self install command, haven't tried it myself. Let me know if later works, I will update the doc.

**Comment by nrbnlulu** [comment]
Cloesing this since I'm not intending to use this currently, Thanks!
